kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
  - name: nginx # list the containers
    image: nginx

    # pod: inside the pod .....asigned default or nginx-->pull the image --> create containers and start the container.
    # same as create docker container.